id: P010724
initial_creation_type: ocr
source_metadata:
  id: bdr:W29298
  title: བཞོ་ལུང
  author: ''
  volumes:
    8684369b4ee441d5adce973e744094ff:
      image_group_id: I5824
      title: ''
      volume_number: 1
      total_pages: 324
